# Generated by Django 3.1.1 on 2020-09-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_key',
            field=models.IntegerField(default=2),
        ),
    ]
