# Generated by Django 3.1.1 on 2020-09-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayApp', '0002_student_active_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verif',
            field=models.BooleanField(default=False),
        ),
    ]
