# Generated by Django 3.1.1 on 2020-09-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PayApp', '0006_auto_20200907_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetdate', models.CharField(max_length=20)),
                ('meettime', models.TimeField()),
                ('mailID', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PayApp.student')),
            ],
        ),
    ]
