# Generated by Django 3.1.1 on 2020-09-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PayApp', '0007_trialmeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=200)),
                ('college_id', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('year_of_study', models.PositiveIntegerField(default=1)),
                ('qr_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_dev', models.BooleanField(default=False)),
                ('portal_code', models.IntegerField(blank=True, null=True)),
                ('github_link', models.CharField(blank=True, max_length=200)),
                ('linkedin_link', models.CharField(blank=True, max_length=200)),
                ('email_token', models.CharField(blank=True, max_length=32, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('phone', models.IntegerField()),
                ('school', models.CharField(max_length=50)),
                ('active_key', models.IntegerField(default=2)),
                ('verif', models.BooleanField(default=False)),
                ('courseapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PayApp.course')),
            ],
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['id'], name='PayApp_user_id_f8219f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['qr_code'], name='PayApp_user_qr_code_a37697_idx'),
        ),
    ]
