# Generated by Django 3.1.1 on 2020-09-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PayApp', '0008_auto_20200911_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conqueresub',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PayApp.enroll'),
        ),
        migrations.AlterField(
            model_name='explorersub',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PayApp.enroll'),
        ),
        migrations.AlterField(
            model_name='freetrialsub',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PayApp.enroll'),
        ),
        migrations.AlterField(
            model_name='trialmeeting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PayApp.enroll'),
        ),
    ]
